<?php

use App\Com_basic;
use Illuminate\Database\Seeder;
use App\User as UserEloquent;
use App\Interviews_stu_questions as insQEloquent;
use App\Interviews_com_questions as incQEloquent;
class userSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	//'u_name', 'email', 'password','u_status','u_tel','u_uni'
//        $user=UserEloquent::create([
//    		'u_name'=>'學生A',
//    		'u_tel'=>'0980365799',
//    		'account'=>'s1110234021',
//    		'u_status'=>0,
//    		'email'=>'s1110234021@nutc.edu.tw',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $user=UserEloquent::create([
//    		'u_name'=>'學生B',
//    		'u_tel'=>'0972012889',
//    		'account'=>'s1110234020',
//    		'u_status'=>0,
//    		'email'=>'s1110234020@nutc.edu.tw',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $user=UserEloquent::create([
//    		'u_name'=>'學生C',
//    		'u_tel'=>'0972012889',
//    		'account'=>'s1110234015',
//    		'u_status'=>0,
//    		'email'=>'s1110234015@nutc.edu.tw',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//         $user1=UserEloquent::create([
//    		'u_name'=>'老師',
//    		'u_tel'=>'0980365799',
//    		'account'=>'teacher123',
//    		'u_status'=>1,
//    		'email'=>'teacher123@nutc.edu.tw',
//    		'password'=>bcrypt('test'),
//             'started'=>1
//    		]);
//          $user2=UserEloquent::create([
//    		'u_name'=>'企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'12345678',
//    		'u_status'=>2,
//    		'email'=>'jamie870116@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $user3=UserEloquent::create([
//            'u_name'=>'系辦',
//            'u_tel'=>'0422115588',
//            'account'=>'admin123',
//            'u_status'=>3,
//            'email'=>'admin@mail.com',
//            'password'=>bcrypt('test'),
//            'started'=>1
//        ]);

//        $sq1=insQEloquent::create([
//            'insQuestion'=>'您感覺實習員對實習機構給予的實習訓練與輔導，是否落實而滿意?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq2=insQEloquent::create([
//            'insQuestion'=>'與實習員訪談後，感受到其對實習工作的滿意度如何?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq3=insQEloquent::create([
//            'insQuestion'=>'實習員談到工作時，其積極參與的程度如何?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq4=insQEloquent::create([
//            'insQuestion'=>'實習員與您的交談、溝通及互動情形?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq5=insQEloquent::create([
//            'insQuestion'=>'實習員對於實習機構給予的輔導瞭解程度如何?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq6=insQEloquent::create([
//            'insQuestion'=>'實習員對於工作量是否合理?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq7=insQEloquent::create([
//            'insQuestion'=>'實習員對於工作中與主管、同事相處情形?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>0,
//        ]);
//        $sq8=insQEloquent::create([
//            'insQuestion'=>'實習員對企業實習，是否滿意?',
//            'insQuestionVer'=>1,
//            'insAnswerType'=>1,
//        ]);
//
////
//        $cq1=incQEloquent::create([
//            'insCQuestion'=>'您感覺實習機構提供實習員實習環境，是否滿意?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq2=incQEloquent::create([
//            'insCQuestion'=>'您感覺實習機構對於實習員訓練與輔導，是否落實?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq3=incQEloquent::create([
//            'insCQuestion'=>'當您請實習機構協助推動實習事宜時，其配合程度?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq4=incQEloquent::create([
//            'insCQuestion'=>'當您與實習機構承辦人員的交談、溝通及互動，其態度如何?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq5=incQEloquent::create([
//            'insCQuestion'=>'實習機構未來是否會優先綠用本系畢業生，您感覺其意願程度?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq6=incQEloquent::create([
//            'insCQuestion'=>'實習機構提供之工作內容與簽約內容、所學是否符合?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq7=incQEloquent::create([
//            'insCQuestion'=>'實習機構是否安排值錢與在職訓練?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);
//        $cq8=incQEloquent::create([
//            'insCQuestion'=>'實習機構是否有工作不當之分配?',
//            'insCQuestionVer'=>1,
//            'insCAnswerType'=>0,
//        ]);


//        $com=UserEloquent::create([
//    		'u_name'=>'aa企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11122256',
//    		'u_status'=>2,
//    		'email'=>'mail@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $comb=Com_basic::create([
//    		'c_name'=>'aa企業',
//    		'cfax'=>'0972012889',
//    		'c_account'=>'11122256',
//    		'caddress'=>'台中市北區三民路三段',
//    		'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>8,
//            'profilePic'=>null,
//    		]);
//        $com2=UserEloquent::create([
//    		'u_name'=>'bb企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11322256',
//    		'u_status'=>2,
//    		'email'=>'mailb@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $com2b=Com_basic::create([
//            'c_name'=>'bb企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11322256',
//            'caddress'=>'台中市北屯區北屯路',
//            'ctypes'=>'',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com3=UserEloquent::create([
//    		'u_name'=>'cc企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11422256',
//    		'u_status'=>2,
//    		'email'=>'mailc@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $com3b=Com_basic::create([
//            'c_name'=>'cc企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11422256',
//            'caddress'=>'台中市南區復興路500號',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>20,
//            'profilePic'=>null,
//        ]);
//        $com4=UserEloquent::create([
//    		'u_name'=>'dd企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11522256',
//    		'u_status'=>2,
//    		'email'=>'maild@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $com4b=Com_basic::create([
//            'c_name'=>'dd企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11522256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>32,
//            'profilePic'=>null,
//        ]);
//        $com5=UserEloquent::create([
//    		'u_name'=>'ee企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11622256',
//    		'u_status'=>2,
//    		'email'=>'maile@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $com5b=Com_basic::create([
//            'c_name'=>'ee企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11622256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>11,
//            'profilePic'=>null,
//        ]);
//        $com6=UserEloquent::create([
//    		'u_name'=>'ff企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'11732256',
//    		'u_status'=>2,
//    		'email'=>'mailf@gmail.com',
//    		'password'=>bcrypt('test'),
//              'started'=>1
//    		]);
//        $com6b=Com_basic::create([
//            'c_name'=>'ff企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11732256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com7=UserEloquent::create([
//    		'u_name'=>'gg企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'15632256',
//    		'u_status'=>2,
//    		'email'=>'mailg@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com7b=Com_basic::create([
//            'c_name'=>'gg企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'15632256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com8=UserEloquent::create([
//    		'u_name'=>'jj企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'25632256',
//    		'u_status'=>2,
//    		'email'=>'mailj@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com8b=Com_basic::create([
//            'c_name'=>'jj企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'25632256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com9=UserEloquent::create([
//    		'u_name'=>'kk企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'35532256',
//    		'u_status'=>2,
//    		'email'=>'mailk@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com9b=Com_basic::create([
//            'c_name'=>'kk企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'35532256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com10=UserEloquent::create([
//    		'u_name'=>'ll企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'21234256',
//    		'u_status'=>2,
//    		'email'=>'maill@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com10b=Com_basic::create([
//            'c_name'=>'ll企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'21234256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com11=UserEloquent::create([
//    		'u_name'=>'oo企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'31234256',
//    		'u_status'=>2,
//    		'email'=>'mailo@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com11b=Com_basic::create([
//            'c_name'=>'oo企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'31234256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com12=UserEloquent::create([
//    		'u_name'=>'qq企業',
//    		'u_tel'=>'0972012889',
//    		'account'=>'15684256',
//    		'u_status'=>2,
//    		'email'=>'mailq@gmail.com',
//    		'password'=>bcrypt('test'),
//            'started'=>1
//    		]);
//        $com12b=Com_basic::create([
//            'c_name'=>'qq企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'15684256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//
//
//
//        $comN=UserEloquent::create([
//            'u_name'=>'abc企業',
//            'u_tel'=>'0972012889',
//            'account'=>'13222256',
//            'u_status'=>2,
//            'email'=>'mail11@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $combN=Com_basic::create([
//            'c_name'=>'abc企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'13222256',
//            'caddress'=>'台中市北區三民路三段',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>8,
//            'profilePic'=>null,
//        ]);
//        $com2N=UserEloquent::create([
//            'u_name'=>'cvb企業',
//            'u_tel'=>'0972012889',
//            'account'=>'65987256',
//            'u_status'=>2,
//            'email'=>'mail22@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com2bN=Com_basic::create([
//            'c_name'=>'cvb企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'65987256',
//            'caddress'=>'台中市北屯區北屯路',
//            'ctypes'=>'',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com3N=UserEloquent::create([
//            'u_name'=>'fdh企業',
//            'u_tel'=>'0972012889',
//            'account'=>'91422256',
//            'u_status'=>2,
//            'email'=>'mail33@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com3bN=Com_basic::create([
//            'c_name'=>'fdh企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'91422256',
//            'caddress'=>'台中市南區復興路500號',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>20,
//            'profilePic'=>null,
//        ]);
//        $com4N=UserEloquent::create([
//            'u_name'=>'tyj企業',
//            'u_tel'=>'0972012889',
//            'account'=>'45612385',
//            'u_status'=>2,
//            'email'=>'mail44@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com4bN=Com_basic::create([
//            'c_name'=>'tyj企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'45612385',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>32,
//            'profilePic'=>null,
//        ]);
//        $com5N=UserEloquent::create([
//            'u_name'=>'qwe企業',
//            'u_tel'=>'0972012889',
//            'account'=>'11622686',
//            'u_status'=>2,
//            'email'=>'mail55@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com5bN=Com_basic::create([
//            'c_name'=>'qwe企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'11622686',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>11,
//            'profilePic'=>null,
//        ]);
//        $com6N=UserEloquent::create([
//            'u_name'=>'uhj企業',
//            'u_tel'=>'0972012889',
//            'account'=>'33332256',
//            'u_status'=>2,
//            'email'=>'mail66@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com6bN=Com_basic::create([
//            'c_name'=>'uhj企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'33332256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com7N=UserEloquent::create([
//            'u_name'=>'asd企業',
//            'u_tel'=>'0972012889',
//            'account'=>'36532256',
//            'u_status'=>2,
//            'email'=>'mail77@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com7N=Com_basic::create([
//            'c_name'=>'asd企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'36532256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com8N=UserEloquent::create([
//            'u_name'=>'uyi企業',
//            'u_tel'=>'0972012889',
//            'account'=>'69532256',
//            'u_status'=>2,
//            'email'=>'mail88@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com8bN=Com_basic::create([
//            'c_name'=>'uyi企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'69532256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com9N=UserEloquent::create([
//            'u_name'=>'adg企業',
//            'u_tel'=>'0972012889',
//            'account'=>'49632256',
//            'u_status'=>2,
//            'email'=>'mail99@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com9bN=Com_basic::create([
//            'c_name'=>'adg企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'49632256',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
//        $com10N=UserEloquent::create([
//            'u_name'=>'iok企業',
//            'u_tel'=>'0972012889',
//            'account'=>'21233357',
//            'u_status'=>2,
//            'email'=>'mai00l@gmail.com',
//            'password'=>bcrypt('test'),
//            'started'=>2
//        ]);
//        $com10bN=Com_basic::create([
//            'c_name'=>'iok企業',
//            'cfax'=>'0972012889',
//            'c_account'=>'21233357',
//            'caddress'=>'',
//            'ctypes'=>'Information',
//            'cdeleteReason'=>null,
//            'cintroduction'=>'',
//            'cempolyee_num'=>12,
//            'profilePic'=>null,
//        ]);
        $com11N=UserEloquent::create([
            'u_name'=>'sad企業',
            'u_tel'=>'0972012889',
            'account'=>'25533357',
            'u_status'=>2,
            'email'=>'mai00al@gmail.com',
            'password'=>bcrypt('test'),
            'started'=>2
        ]);
        $com11bN=Com_basic::create([
            'c_name'=>'sad企業',
            'cfax'=>'0972012889',
            'c_account'=>'25533357',
            'caddress'=>'',
            'ctypes'=>'Information',
            'cdeleteReason'=>null,
            'cintroduction'=>'',
            'cempolyee_num'=>12,
            'profilePic'=>null,
        ]);
    }
}
